runtime: nodejs10

handlers:
    - url: /
      static_files: build/index.html
      upload: build/index.html

    - url: /
      static_dir: build

env_variables:
  SERVER_URL: 'https://api-dot-feeding-schedule.uc.r.appspot.com'